### ISSUE TITLE
some issues

### ISSUE THREAD

**Issue by sckush** [shirsig/enemybars#2]
Hey, first off thanks for the addon. I do however have problems with it.

(1) i use it in raid , it makes me very low fps and  my screen always gets stuck, i dont know where is problem, and it is forbidden thats gonna be ok. 
(2) some time it Into two boxes.

**Comment by shirsig** [comment]
I've never used it in a raid but I'll test it when I can. Not sure how being in a raid could have an effect on its performance though, besides more going on in general/processing needed for other things.

>some time it Into two boxes

what?

**Comment by sckush** [comment]
i mean split into two enemybars lists sometime

**Comment by shirsig** [comment]
with the newest version?

**Comment by sckush** [comment]
yep

**Comment by shirsig** [comment]
are you sure you installed it correctly? can't imagine how this could happen with a new version.

**Comment by sckush** [comment]
Yes, at the same time the two window is in Azshara to pvp

**Comment by shirsig** [comment]
can you make a screenshot?

**Comment by sckush** [comment]
sry no. but im sure its happend , only once.  

You can repair the situation of lag phase（raid） and always have some voice reflash

**Comment by shirsig** [comment]
> always have some voice reflash

What does that mean?

**Comment by sckush** [comment]
When there is someone nearby, the enemy will be shown and there is a note , sometime the voice always repeat

**Comment by shirsig** [comment]
You mean the sound effect is repeating? Which one? I've once had it repeat the effect from a disappearing bar for some reason but haven't found out why/if it still happens.

**Comment by sckush** [comment]
I can't describe it （Like a brief breath）. 
This is a very good addons thanks to the creation of this. 
Hope it gets more and more perfect.
Thank you for your unselfish dedication.

**Comment by shirsig** [comment]
Well, there are 3 sound effects. One when the first bar appears (loud alert), one when a new bar appears when there already are bars (sort of "shuffling" sound) and the sound of a bar disappearing. I assume you're talking about the 2nd? What do you mean by repeat though? More than once for every bar added?

**Comment by sckush** [comment]
yep its 2nd. This addons is like a radar continuous scanning.  i think it repeated the already exists bar

**Comment by shirsig** [comment]
changed the scanning a bit to make it less aggressive, maybe that will help with the raid performance
